In [1]:
import os
import json
from glob import glob

# Dataset paths
root_dir = "/kaggle/input/merged-potholes-speedbumps/merged"
train_image_dir = os.path.join(root_dir, "images", "train")
test_image_dir = os.path.join(root_dir, "images", "test")
valid_image_dir = os.path.join(root_dir, "images", "valid")
annotation_dir = os.path.join(root_dir, "annotations")

# COCO annotation files
train_json_path = os.path.join(annotation_dir, "merged_annotations_train.json")
valid_json_path = os.path.join(annotation_dir, "merged_annotations_valid.json")
test_json_path = os.path.join(annotation_dir, "merged_annotations_test.json")
print(root_dir)
print(train_image_dir)
print(test_image_dir)
print(valid_image_dir)
print(annotation_dir)
print(train_json_path)
print(test_json_path)
print(valid_json_path)

/kaggle/input/merged-potholes-speedbumps/merged
/kaggle/input/merged-potholes-speedbumps/merged/images/train
/kaggle/input/merged-potholes-speedbumps/merged/images/test
/kaggle/input/merged-potholes-speedbumps/merged/images/valid
/kaggle/input/merged-potholes-speedbumps/merged/annotations
/kaggle/input/merged-potholes-speedbumps/merged/annotations/merged_annotations_train.json
/kaggle/input/merged-potholes-speedbumps/merged/annotations/merged_annotations_test.json
/kaggle/input/merged-potholes-speedbumps/merged/annotations/merged_annotations_valid.json

In [2]:
# Load JSON files
with open(train_json_path) as f:
    train_data = json.load(f)

with open(valid_json_path) as f:
    valid_data = json.load(f)

with open(test_json_path) as f:
    test_data = json.load(f)

# Print data stats
print("Train images:", len(train_data["images"]))
print("Validation images:", len(valid_data["images"]))
print("Test images:", len(test_data["images"]))

Train images: 2392
Validation images: 350
Test images: 163

In [3]:
# Check a few actual image files
train_image_files = glob(os.path.join(train_image_dir, "*.jpg"))
print("train images:",len(train_image_files), train_image_files[:5])
print("------------------------------------------------------------")
test_image_files = glob(os.path.join(test_image_dir, "*.jpg"))
print("test images:",len(test_image_files), test_image_files[:5])
print("------------------------------------------------------------")
valid_image_files = glob(os.path.join(valid_image_dir, "*.jpg"))
print("valid images:",len(valid_image_files), valid_image_files[:5])
print("------------------------------------------------------------")

train images: 2392 ['/kaggle/input/merged-potholes-speedbumps/merged/images/train/810_jpg.rf.723e951e6c40b9e34990531789239880.jpg', '/kaggle/input/merged-potholes-speedbumps/merged/images/train/299_jpg.rf.9b5352ef16c9b85a80b528d836ea5d72.jpg', '/kaggle/input/merged-potholes-speedbumps/merged/images/train/Image00323_jpg.rf.b74be24c67b8a31cb8a566e43780778e.jpg', '/kaggle/input/merged-potholes-speedbumps/merged/images/train/images-15-_jpg.rf.82ae4b6bb73f71ff10bc94a61719fe42.jpg', '/kaggle/input/merged-potholes-speedbumps/merged/images/train/img-551_jpg.rf.2b6aca4deb8d05243dbefe85f26bbcf3.jpg']
------------------------------------------------------------
test images: 163 ['/kaggle/input/merged-potholes-speedbumps/merged/images/test/1168_jpg.rf.cce7a12e0d8a4574a61fc260ee89a95b.jpg', '/kaggle/input/merged-potholes-speedbumps/merged/images/test/1917_jpg.rf.70e463f4123d23b72d0beefdd0ff9e1a.jpg', '/kaggle/input/merged-potholes-speedbumps/merged/images/test/753_jpg.rf.8f3348cf72ee6443c19e119dd95ca710.jpg', '/kaggle/input/merged-potholes-speedbumps/merged/images/test/img-65_jpg.rf.9e22afc3c2cf318239352e43a97a7241.jpg', '/kaggle/input/merged-potholes-speedbumps/merged/images/test/img-631_jpg.rf.86bcf4f20ded917eb31426fe83043df3.jpg']
------------------------------------------------------------
valid images: 350 ['/kaggle/input/merged-potholes-speedbumps/merged/images/valid/img-382_jpg.rf.f150d3d57a37b68447bb670ba15cbd8f.jpg', '/kaggle/input/merged-potholes-speedbumps/merged/images/valid/789_jpg.rf.f8e5e4e98c1c10560b146570ae236828.jpg', '/kaggle/input/merged-potholes-speedbumps/merged/images/valid/img-153_jpg.rf.ba410ca055afdae3cb292f1cdede8c08.jpg', '/kaggle/input/merged-potholes-speedbumps/merged/images/valid/1390_jpg.rf.b7da79c777654162ff1ceff191f4e5f2.jpg', '/kaggle/input/merged-potholes-speedbumps/merged/images/valid/img-556_jpg.rf.1c89285dfe3675fd0e4a7958c48a7a87.jpg']
------------------------------------------------------------

In [4]:
cd ..

/kaggle

In [5]:
!pip install pycocotools numpy opencv-python tqdm tensorboard tensorboardX pyyaml webcolors
!pip install torch
!pip install torchvision

Requirement already satisfied: pycocotools in /usr/local/lib/python3.11/dist-packages (2.0.8)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (1.26.4)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.11/dist-packages (4.11.0.86)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (4.67.1)
Requirement already satisfied: tensorboard in /usr/local/lib/python3.11/dist-packages (2.18.0)
Collecting tensorboardX
  Downloading tensorboardX-2.6.2.2-py2.py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (6.0.2)
Requirement already satisfied: webcolors in /usr/local/lib/python3.11/dist-packages (24.11.1)
Requirement already satisfied: matplotlib>=2.1.0 in /usr/local/lib/python3.11/dist-packages (from pycocotools) (3.7.2)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy) (2025.1.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy) (2022.1.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy) (2.4.1)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.11/dist-packages (from tensorboard) (1.4.0)
Requirement already satisfied: grpcio>=1.48.2 in /usr/local/lib/python3.11/dist-packages (from tensorboard) (1.72.0rc1)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.11/dist-packages (from tensorboard) (3.7)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from tensorboard) (25.0)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in /usr/local/lib/python3.11/dist-packages (from tensorboard) (3.20.3)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard) (75.2.0)
Requirement already satisfied: six>1.9 in /usr/local/lib/python3.11/dist-packages (from tensorboard) (1.17.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from tensorboard) (3.1.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.1.0->pycocotools) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.1.0->pycocotools) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.1.0->pycocotools) (4.57.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.1.0->pycocotools) (1.4.8)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.1.0->pycocotools) (11.1.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.1.0->pycocotools) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.1.0->pycocotools) (2.9.0.post0)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from werkzeug>=1.0.1->tensorboard) (3.0.2)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy) (2022.1.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy) (1.3.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy) (2024.2.0)
Downloading tensorboardX-2.6.2.2-py2.py3-none-any.whl (101 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 4.6 MB/s eta 0:00:00
Installing collected packages: tensorboardX
Successfully installed tensorboardX-2.6.2.2
Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (2.6.0+cu124)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch) (4.13.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch) (2025.3.2)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch) (3.0.2)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.2 MB/s eta 0:00:000:00:0100:01
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.9 MB/s eta 0:00:000:00:0100:01
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 6.4 MB/s eta 0:00:000:00:0100:01
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 27.5 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 10.8 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 3.1 MB/s eta 0:00:000:00:0100:01
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 73.2 MB/s eta 0:00:00:00:0100:01
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.9.41
    Uninstalling nvidia-nvjitlink-cu12-12.9.41:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.9.41
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.10.19
    Uninstalling nvidia-curand-cu12-10.3.10.19:
      Successfully uninstalled nvidia-curand-cu12-10.3.10.19
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.4.0.6
    Uninstalling nvidia-cufft-cu12-11.4.0.6:
      Successfully uninstalled nvidia-cufft-cu12-11.4.0.6
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.9.0.13
    Uninstalling nvidia-cublas-cu12-12.9.0.13:
      Successfully uninstalled nvidia-cublas-cu12-12.9.0.13
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.9.5
    Uninstalling nvidia-cusparse-cu12-12.5.9.5:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.9.5
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.7.4.40
    Uninstalling nvidia-cusolver-cu12-11.7.4.40:
      Successfully uninstalled nvidia-cusolver-cu12-11.7.4.40
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127
Requirement already satisfied: torchvision in /usr/local/lib/python3.11/dist-packages (0.21.0+cu124)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from torchvision) (1.26.4)
Requirement already satisfied: torch==2.6.0 in /usr/local/lib/python3.11/dist-packages (from torchvision) (2.6.0+cu124)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.11/dist-packages (from torchvision) (11.1.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchvision) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchvision) (4.13.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchvision) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchvision) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchvision) (2025.3.2)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchvision) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchvision) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchvision) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchvision) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchvision) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchvision) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchvision) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchvision) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchvision) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchvision) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchvision) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchvision) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchvision) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchvision) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchvision) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch==2.6.0->torchvision) (1.3.0)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy->torchvision) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy->torchvision) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy->torchvision) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy->torchvision) (2025.1.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy->torchvision) (2022.1.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy->torchvision) (2.4.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch==2.6.0->torchvision) (3.0.2)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy->torchvision) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy->torchvision) (2022.1.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy->torchvision) (1.3.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy->torchvision) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy->torchvision) (2024.2.0)

In [6]:
import pandas as pd
def coco_to_csv(json_data, image_dir):
    id_to_filename = {img['id']: img['file_name'] for img in json_data['images']}
    id_to_class = {cat['id']: cat['name'] for cat in json_data['categories']}

    rows = []
    for ann in json_data['annotations']:
        image_id = ann['image_id']
        file_name = id_to_filename.get(image_id)
        if not file_name:
            continue  # skip if image_id not found

        image_path = os.path.join(image_dir, file_name)
        if not os.path.exists(image_path):
            # Sometimes file_name might be wrong or file might be missing
            print(f"Warning: Image not found: {image_path}")
            continue

        bbox = ann['bbox']
        x_min, y_min, width, height = bbox
        x_max = x_min + width
        y_max = y_min + height

        category_id = ann['category_id']
        class_name = id_to_class.get(category_id, "undefined")
        rows.append([image_path, x_min, y_min, x_max, y_max, class_name])

    df = pd.DataFrame(rows, columns=["image_path", "xmin", "ymin", "xmax", "ymax", "class_name"])
    return df

In [7]:
# Convert
train_df = coco_to_csv(train_data, train_image_dir).sample(frac=1, random_state=42).reset_index(drop=True)
valid_df = coco_to_csv(valid_data, valid_image_dir).sample(frac=1, random_state=42).reset_index(drop=True)
test_df = coco_to_csv(test_data, test_image_dir).sample(frac=1, random_state=42).reset_index(drop=True)

In [8]:
train_df.head()

,image_path,xmin,ymin,xmax,ymax,class_name
0,/kaggle/input/merged-potholes-speedbumps/merge...,293,325,445.0,389.0,pothole
1,/kaggle/input/merged-potholes-speedbumps/merge...,243,70,640.0,123.0,speedbump
2,/kaggle/input/merged-potholes-speedbumps/merge...,100,178,611.0,263.0,speedbump
3,/kaggle/input/merged-potholes-speedbumps/merge...,0,142,374.0,299.0,pothole
4,/kaggle/input/merged-potholes-speedbumps/merge...,57,98,145.0,141.0,pothole

In [9]:
test_df.head(10)

,image_path,xmin,ymin,xmax,ymax,class_name
0,/kaggle/input/merged-potholes-speedbumps/merge...,572,58,672.0,125.0,pothole
1,/kaggle/input/merged-potholes-speedbumps/merge...,163,90,332.0,233.0,pothole
2,/kaggle/input/merged-potholes-speedbumps/merge...,359,221,462.0,310.0,pothole
3,/kaggle/input/merged-potholes-speedbumps/merge...,1,111,146.0,128.0,pothole
4,/kaggle/input/merged-potholes-speedbumps/merge...,3,140,393.0,263.0,pothole
5,/kaggle/input/merged-potholes-speedbumps/merge...,456,43,556.0,100.0,pothole
6,/kaggle/input/merged-potholes-speedbumps/merge...,3,48,519.0,184.0,speedbump
7,/kaggle/input/merged-potholes-speedbumps/merge...,43,270,615.0,360.0,speedbump
8,/kaggle/input/merged-potholes-speedbumps/merge...,282,247,438.0,341.0,pothole
9,/kaggle/input/merged-potholes-speedbumps/merge...,0,83,622.0,388.0,speedbump

In [10]:
valid_df.head()

,image_path,xmin,ymin,xmax,ymax,class_name
0,/kaggle/input/merged-potholes-speedbumps/merge...,377,180,532.0,219.0,pothole
1,/kaggle/input/merged-potholes-speedbumps/merge...,166,232,561.0,398.0,pothole
2,/kaggle/input/merged-potholes-speedbumps/merge...,252,254,268.0,274.0,pothole
3,/kaggle/input/merged-potholes-speedbumps/merge...,28,226,581.0,293.0,speedbump
4,/kaggle/input/merged-potholes-speedbumps/merge...,261,230,418.0,261.0,pothole

In [11]:
train_df.to_csv("/kaggle/working/train.csv", index=False)
valid_df.to_csv("/kaggle/working/valid.csv", index=False)
test_df.to_csv("/kaggle/working/test.csv", index=False)

In [13]:

!python /kaggle/input/efficientdet/pytorch/default/1/efficientdet/train.py \
  --dataset csv \
  --csv_train /kaggle/working/train.csv \
  --csv_val /kaggle/working/valid.csv \
  --csv_classes /kaggle/working/classes.csv \
  --batch_size 4 \
  --num_epochs 30 \
  --depth 2

Traceback (most recent call last):
  File "/kaggle/input/efficientdet/pytorch/default/1/efficientdet/train.py", line 8, in <module>
    from src.model import EfficientDet
  File "/kaggle/input/efficientdet/pytorch/default/1/efficientdet/src/model.py", line 4, in <module>
    from efficientnet_pytorch import EfficientNet as EffNet
ModuleNotFoundError: No module named 'efficientnet_pytorch'

In [ ]:
from efficientdet import EfficientDet
import torch

# Load model
model = EfficientDet(compound_coef=2, num_classes=2)
model.load_state_dict(torch.load('path_to_saved_model.pth'))
model.eval()